services:
  emprestimo:
    build: ./emprestimo
    volumes:
      - ./emprestimo:/usr/src/app
      - emprestimo_logs:/var/log/emprestimo
    ports:
      - "3001:8000"
    env_file:
      - ./envs/postgres.env
      - ./envs/redis.env
    depends_on:
      - emprestimo_db

  emprestimo_db:
    image: postgres:16.3-bullseye
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/postgres.env

  emprestimo_redis:
    container_name: emprestimo_redis
    image: bitnami/redis:7.2
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  emprestimo_logs:
  postgres_data:
  redis_data:
