services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: backoffice_db
    networks:
      - backoffice_network
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dev!123
      - POSTGRES_PORT=5432

  api:
    build: .
    container_name: backoffice_api
    networks:
      - backoffice_network
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - .:/app

# volumes:
#   postgres_data: {}
networks:
  backoffice_network:
    driver: bridge

  